# Generated by Django 5.2.7 on 2026-06-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_created_at_user_phone_number_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='preffered_location',
            field=models.CharField(default='belhar', max_length=20),
        ),
    ]
