"""
Django settings for findmyvibe_backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Reads from the environment so a real deployment isn't stuck with the
# committed dev key; falls back to the original dev-only key so nothing
# breaks locally if SECRET_KEY isn't set.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    'django-insecure-lt8c)-b50t)z@c)@f^6uxxop49f0ob^4o6lv=i$%bd7j#29_bz',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "False"

ALLOWED_HOSTS = [h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'findmyvibe',
    'accounts',
    'corsheaders',
    # Phase 0 fix: djangorestframework is in requirement.txt and REST_FRAMEWORK
    # settings already existed below, but the app itself was never registered,
    # so none of it was actually active.
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',


]
CORS_ALLOWED_ORIGINS=[
    'http://127.0.0.1:5500',
    'http://localhost:5500',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://127.0.0.1:3000',
    'http://localhost:3000',
    'http://127.0.0.1:55433',
    'http://127.0.0.1:54165',
    'https://find-my-vibe.onrender.com'
]
# Security pass: this was a hardcoded localhost-only list with no way to
# add a real production frontend origin without editing this file. Extend
# (not replace) it from an env var so local dev keeps working unchanged.
CORS_ALLOWED_ORIGINS += [o for o in os.environ.get("DJANGO_EXTRA_CORS_ORIGINS", "").split(",") if o]

CORS_ALLOW_CREDENTIALS = True

from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers) + ["x-csrftoken"]

# Needed because the frontend (e.g. :5500) and backend (:8000) are different
# ports/origins even though they're the same host - Django's CSRF middleware
# checks the request's Origin header against this list for any non-GET
# request, separately from the SameSite cookie behaviour.
CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS)

ROOT_URLCONF = 'findmyvibe_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': [],
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'findmyvibe_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static')
]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / 'static']
REST_FRAMEWORK = {
    # Phase 0 fix: frontend calls the API with `credentials: 'include'` (session
    # cookies), not an Authorization header, so SessionAuthentication needs to be
    # enabled too or every authenticated DRF endpoint will 401 for the existing
    # login flow. TokenAuthentication is kept for future mobile/other clients.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,
    # Security pass: the API had no rate limiting at all - anyone could hit
    # any endpoint (including the admin reset_password/toggle_active actions,
    # or just hammer /api/properties/) as fast as their connection allowed.
    # These are deliberately generous dev-friendly numbers, not tuned for a
    # real deployment - tighten per-endpoint if you need stricter limits.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/minute',
        'user': '300/minute',
    },
}

# Rate-limiting (DRF throttling above, and the login attempt limiter in
# accounts/views.py) needs a cache backend. No CACHES setting existed, so
# Django was implicitly using its per-process LocMemCache default - that's
# fine for local dev but does NOT share state across multiple worker
# processes/servers. A real deployment needs a shared cache (e.g. Redis)
# for rate limiting to actually work correctly.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

# Phase 0 fix: no MEDIA settings existed, so uploaded profile pictures and
# property images had nowhere to be written to or served from.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'accounts.User'
AUTHENTICATION_BACKENDS = [
    "accounts.backends.EmailOrUsernameModelBackend",
    "django.contrib.auth.backends.ModelBackend",
]
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "accounts:login"

# Security pass: production hardening, gated behind DEBUG so local dev
# (DJANGO_DEBUG=True, the default) is completely unaffected. None of this
# was configured before - a deployment with DJANGO_DEBUG=False would have
# been running with none of Django's standard production protections.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7  # 1 week - raise once confident HTTPS is stable
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    # ALLOWED_HOSTS already reads from DJANGO_ALLOWED_HOSTS. For CORS/CSRF,
    # set DJANGO_EXTRA_CORS_ORIGINS (see CORS_ALLOWED_ORIGINS above) to your
    # real frontend domain(s) - the localhost entries stay for local testing
    # against a production-configured backend, but should not be the only
    # origins a real deployment trusts.