# Generated by Django 6.0.6 on 2026-07-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('std_number', models.CharField(max_length=10)),
                ('alternate_phone_number', models.IntegerField(default=0)),
                ('phone_number', models.CharField(max_length=10)),
                ('D_O_B', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('home_address', models.TextField(max_length=255)),
                ('e_fname', models.CharField(max_length=100)),
                ('e_lname', models.CharField(max_length=100)),
                ('e_relationship', models.CharField(max_length=100)),
                ('e_d_o_b', models.DateField(max_length=100)),
                ('e_gender', models.CharField(max_length=6)),
                ('e_email', models.EmailField(max_length=255)),
                ('e_phone_no', models.IntegerField()),
                ('uni', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('Course', models.CharField(max_length=255)),
                ('E_Y_O_G', models.IntegerField()),
                ('sponsor', models.CharField(max_length=100)),
                ('allergy', models.CharField(default=None, max_length=500)),
                ('med_cond', models.CharField(max_length=500)),
                ('Disabilities', models.BooleanField(default=False)),
                ('med_aid', models.BooleanField(default=False)),
                ('Medial_Aid_Provider', models.CharField(max_length=500)),
                ('medical_aid_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='student_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('landlord', 'Landlord'), ('admin', 'Admin')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='student_user_permissions', to='auth.permission'),
        ),
        migrations.DeleteModel(
            name='LandlordProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
